### ISSUE TITLE
salt execution module junos.install_config with invalid mode throws exception ValueError: unsupported action: test	

### ISSUE THREAD

**Issue by rsmekala** [Juniper/salt#103]
### Description of Issue/Question

```
root@nms5-salt-master-b:/srv/salt# salt "vmx1" junos.install_config salt://config.set mode=test

vmx1:
    The minion function caused an exception: Traceback (most recent call last):
      File "/usr/local/lib/python2.7/site-packages/salt/minion.py", line 1660, in _thread_return
        return_data = minion_instance.executors[fname](opts, data, func, args, kwargs)
      File "/usr/local/lib/python2.7/site-packages/salt/executors/direct_call.py", line 12, in execute
        return func(*args, **kwargs)
      File "/usr/local/lib/python2.7/site-packages/salt/modules/junos.py", line 99, in wrapper
        return function(*args, **kwargs)
      File "/usr/local/lib/python2.7/site-packages/salt/modules/junos.py", line 921, in install_config
        with Config(conn, mode=db_mode) as cu:
      File "/usr/local/lib/python2.7/site-packages/jnpr/junos/utils/config.py", line 832, in __enter__
        }.get(self.mode, _unsupported_option)()
      File "/usr/local/lib/python2.7/site-packages/jnpr/junos/utils/config.py", line 817, in _unsupported_option
        raise ValueError("unsupported action: {}".format(self.mode))
    ValueError: unsupported action: test

```

**Comment by rsmekala** [comment]
Close PR: [1429965]https://gnats.juniper.net/web/default/1429965-1l)
