### ISSUE TITLE
salt execution module junos.install_config with mode exclusive throws exception LockError: LockError(severity: error, bad_element: None, message: configuration database modified)

### ISSUE THREAD

**Issue by rsmekala** [Juniper/salt#105]
### Description of Issue

```
root@nms5-salt-master-b:/srv/salt# salt "vmx1" junos.install_config salt://baseline-config.conf mode=exclusive comment="testing1" format=text update=True
[WARNING ] /usr/local/lib/python2.7/site-packages/salt/payload.py:149: DeprecationWarning: encoding is deprecated, Use raw=False instead.
  ret = msgpack.loads(msg, use_list=True, ext_hook=ext_type_decoder, encoding=encoding)

vmx1:
    The minion function caused an exception: Traceback (most recent call last):
      File "/usr/local/lib/python2.7/site-packages/salt/minion.py", line 1660, in _thread_return
        return_data = minion_instance.executors[fname](opts, data, func, args, kwargs)
      File "/usr/local/lib/python2.7/site-packages/salt/executors/direct_call.py", line 12, in execute
        return func(*args, **kwargs)
      File "/usr/local/lib/python2.7/site-packages/salt/modules/junos.py", line 99, in wrapper
        return function(*args, **kwargs)
      File "/usr/local/lib/python2.7/site-packages/salt/modules/junos.py", line 921, in install_config
        with Config(conn, mode=db_mode) as cu:
      File "/usr/local/lib/python2.7/site-packages/jnpr/junos/utils/config.py", line 832, in __enter__
        }.get(self.mode, _unsupported_option)()
      File "/usr/local/lib/python2.7/site-packages/jnpr/junos/utils/config.py", line 809, in _open_configuration_exclusive
        return self.lock()
      File "/usr/local/lib/python2.7/site-packages/jnpr/junos/utils/config.py", line 568, in lock
        raise LockError(rsp=err.rsp)
    LockError: LockError(severity: error, bad_element: None, message: configuration database modified)
```

**Comment by rsmekala** [comment]
Closed PR: [1429992](https://gnats.juniper.net/web/default/1429992-1)
