### ISSUE TITLE
salt execution module junos.install_os with invalid image name throws exception and help information is not dispalyed

### ISSUE THREAD

**Issue by rsmekala** [Juniper/salt#109]
### Description of Issue/Question

```
root@nms5-salt-master-b:~# salt "vmx1" junos.install_os test no_copy=False

vmx1:
    The minion function caused an exception: Traceback (most recent call last):
      File "/usr/local/lib/python2.7/site-packages/salt/minion.py", line 1660, in _thread_return
        return_data = minion_instance.executors[fname](opts, data, func, args, kwargs)
      File "/usr/local/lib/python2.7/site-packages/salt/executors/direct_call.py", line 12, in execute
        return func(*args, **kwargs)
      File "/usr/local/lib/python2.7/site-packages/salt/modules/junos.py", line 99, in wrapper
        return function(*args, **kwargs)
      File "/usr/local/lib/python2.7/site-packages/salt/modules/junos.py", line 1087, in install_os
        __salt__['cp.get_file'](path, image_cached_path)
      File "/usr/local/lib/python2.7/site-packages/salt/modules/cp.py", line 301, in get_file
        gzip)
      File "/usr/local/lib/python2.7/site-packages/salt/fileclient.py", line 1120, in get_file
        path = self._check_proto(path)
      File "/usr/local/lib/python2.7/site-packages/salt/fileclient.py", line 114, in _check_proto
        raise MinionError('Unsupported path: {0}'.format(path))
    MinionError: Unsupported path: test
ERROR: Minions returned with non-zero exit code

```

**Comment by rsmekala** [comment]
Merged to 2019.2
