### ISSUE TITLE
Add exception handling in Junos proxy to handle device connect errors

### ISSUE THREAD

**Issue by akbhat** [Juniper/salt#56]
### Description of Issue/Question
Add exception handling to junos proxy init around thisproxy['conn'].open() to handle connection errors 

### Logs from /var/log/salt/proxy
2018-06-30 09:52:37,833 [salt.minion      :1014][CRITICAL][3637] Unexpected error while connecting to master1
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/minion.py", line 997, in _connect_minion
    yield minion.connect_master(failed=failed)
  File "/usr/lib/python2.7/dist-packages/tornado/gen.py", line 870, in run
    value = future.result()
  File "/usr/lib/python2.7/dist-packages/tornado/concurrent.py", line 215, in result
    raise_exc_info(self._exc_info)
  File "/usr/lib/python2.7/dist-packages/tornado/gen.py", line 876, in run
    yielded = self.gen.throw(*exc_info)
  File "/usr/lib/python2.7/dist-packages/salt/minion.py", line 1188, in connect_master
    yield self._post_master_init(master)
  File "/usr/lib/python2.7/dist-packages/tornado/gen.py", line 870, in run
    value = future.result()
  File "/usr/lib/python2.7/dist-packages/tornado/concurrent.py", line 215, in result
    raise_exc_info(self._exc_info)
  File "/usr/lib/python2.7/dist-packages/tornado/gen.py", line 879, in run
    yielded = self.gen.send(value)
  File "/usr/lib/python2.7/dist-packages/salt/minion.py", line 3590, in _post_master_init
    proxy_init_fn(self.opts)
  File "/usr/lib/python2.7/dist-packages/salt/proxy/junos.py", line 109, in init
    thisproxy['conn'].open()
  File "/usr/local/lib/python2.7/dist-packages/jnpr/junos/device.py", line 1268, in open
    raise EzErrors.ConnectRefusedError(self)
ConnectRefusedError: ConnectRefusedError(192.168.122.90)

2018-06-30 09:52:38,215 [salt.minion      :433 ][ERROR   ][3637] Exception argument of type 'bool' is not iterable occurred in scheduled job

### Versions Report
root@minion1:~# salt --versions
Salt Version:
           Salt: 2018.3.1
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.21.1
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.12 (default, Dec  4 2017, 14:50:18)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 17.0.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.6
 
System Versions:
           dist: Ubuntu 16.04 xenial
         locale: UTF-8
        machine: x86_64
        release: 4.4.0-38-generic
         system: Linux
        version: Ubuntu 16.04 xenial

**Comment by rsmekala** [comment]
Merged to saltstack develop via saltstack#51164
