### ISSUE TITLE
Salt execution module junos.cli with invalid dest="" throws exception FileNotFoundError: [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by rsmekala** [Juniper/salt#86]
### Description of Issue/Question
salt execution module junos.cli with invalid dest="" throws exception FileNotFoundError: [Errno 2] No such file or directory..
 Exception not handled ..

### Logs

root@testbase:/srv/salt# salt "vmx1" junos.cli "show version" dev_timeout=60 dest=""
[WARNING ] /usr/local/lib/python3.4/dist-packages/salt/transport/ipc.py:287: DeprecationWarning: encoding is deprecated, Use raw=False instead.
  self.unpacker = msgpack.Unpacker(encoding=encoding)

[WARNING ] /usr/local/lib/python3.4/dist-packages/salt/payload.py:149: DeprecationWarning: encoding is deprecated, Use raw=False instead.
  ret = msgpack.loads(msg, use_list=True, ext_hook=ext_type_decoder, encoding=encoding)

vmx1:
    The minion function caused an exception: Traceback (most recent call last):
      File "/usr/local/lib/python3.4/dist-packages/salt/minion.py", line 1660, in _thread_return
        return_data = minion_instance.executors[fname](opts, data, func, args, kwargs)
      File "/usr/local/lib/python3.4/dist-packages/salt/executors/direct_call.py", line 12, in execute
        return func(*args, **kwargs)
      File "/usr/local/lib/python3.4/dist-packages/salt/modules/junos.py", line 91, in wrapper
        result = function(*args, **kwargs)
      File "/usr/local/lib/python3.4/dist-packages/salt/modules/junos.py", line 689, in cli
        with salt.utils.files.fopen(op['dest'], 'w') as fp:
      File "/usr/local/lib/python3.4/dist-packages/salt/utils/files.py", line 399, in fopen
        f_handle = open(*args, **kwargs)  # pylint: disable=resource-leakage
    FileNotFoundError: [Errno 2] No such file or directory: ''
ERROR: Minions returned with non-zero exit code

**Comment by rsmekala** [comment]
Closed PR: [1427511](https://gnats.juniper.net/web/default/1427511-1)
