### ISSUE TITLE
Junos syslog engine doesn't startup in Python 3.x environment 

### ISSUE THREAD

**Issue by rsmekala** [Juniper/salt#91]
### Description of Issue/Question

In Python3.x environment, `junos_syslog` engine doesn't start up and quits with the following error message:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/salt/engines/__init__.py", line 132, in run
    self.engine[self.fun](**kwargs)
  File "/usr/local/lib/python3.4/dist-packages/salt/engines/junos_syslog.py", line 394, in start
    reactor.listenUDP(port, _SyslogServerFactory(kwargs))
  File "/usr/local/lib/python3.4/dist-packages/salt/engines/junos_syslog.py", line 246, in __init__
    self.obj = _Parser()
  File "/usr/local/lib/python3.4/dist-packages/salt/engines/junos_syslog.py", line 147, in __init__
    month = Word(string.uppercase, string.lowercase, exact=3)
AttributeError: 'module' object has no attribute 'uppercase'
```

The fix is already present in develop. Needs porting.

Commit ID: 93ebb9b3d12575cc35f687fc4f8fcf42608b1b34

**Comment by rsmekala** [comment]
Test suite changed to operate in Python>2.7.6, <3.x.

Closed PR: [1428457](https://gnats.juniper.net/web/default/1428457-1)
