### ISSUE TITLE
Applying salt state file with function junos.rollback fails with TypeError: rollback() takes exactly 0 arguments (1 given)

### ISSUE THREAD

**Issue by rsmekala** [Juniper/salt#98]
### Description of Issue/Question

```
Applying salt state file with function junos.rollback fails with TypeError: rollback() takes exactly 0 arguments (1 given)

root@nms5-salt-master-b:/srv/salt# cat junos_rollback.sls 
rollback the changes:
  junos.rollback:
   - id: 0


root@nms5-salt-master-b:/srv/salt# salt "vmx1" state.apply junos_rollback
[WARNING ] /usr/local/lib/python2.7/site-packages/salt/payload.py:149: DeprecationWarning: encoding is deprecated, Use raw=False instead.
  ret = msgpack.loads(msg, use_list=True, ext_hook=ext_type_decoder, encoding=encoding)

[ERROR   ] An exception occurred in this state: Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/salt/state.py", line 1933, in call
    **cdata['kwargs'])
  File "/usr/local/lib/python2.7/site-packages/salt/loader.py", line 1939, in wrapper
    return f(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/salt/states/junos.py", line 27, in wrapper
    ret = function(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/salt/states/junos.py", line 195, in rollback
    ret['changes'] = __salt__['junos.rollback'](id, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/salt/modules/junos.py", line 99, in wrapper
    return function(*args, **kwargs)
TypeError: rollback() takes exactly 0 arguments (1 given)

vmx1:
----------
          ID: rollback the changes
    Function: junos.rollback
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "/usr/local/lib/python2.7/site-packages/salt/state.py", line 1933, in call
                  **cdata['kwargs'])
                File "/usr/local/lib/python2.7/site-packages/salt/loader.py", line 1939, in wrapper
                  return f(*args, **kwargs)
                File "/usr/local/lib/python2.7/site-packages/salt/states/junos.py", line 27, in wrapper
                  ret = function(*args, **kwargs)
                File "/usr/local/lib/python2.7/site-packages/salt/states/junos.py", line 195, in rollback
                  ret['changes'] = __salt__['junos.rollback'](id, **kwargs)
                File "/usr/local/lib/python2.7/site-packages/salt/modules/junos.py", line 99, in wrapper
                  return function(*args, **kwargs)
              TypeError: rollback() takes exactly 0 arguments (1 given)
     Started: 18:25:55.580951
    Duration: 11.466 ms
     Changes:   

Summary for vmx1
------------
Succeeded: 0
Failed:    1
------------
Total states run:     1
Total run time:  11.466 ms
ERROR: Minions returned with non-zero exit code
```

**Comment by rsmekala** [comment]
Closed PR: [1429609](https://gnats.juniper.net/web/default/1429609-1)
